# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cdcea5c25fb5b4faacc6e949c5a3efb3b8cfb6ca347a7bf07ba93665c0e926869ae8a9ec92c26adbe389395be527e5ed7ef3e2c56992b878d96a0ebeaae4281e

test:
  secret_key_base: 4b014411d33aa5175f7068c829cfdee64bded2d574e5da5acb5a0ed2aef2d0e3f6bbb3a9641dd86c33c5eac178861d82bab34c37d0965017dc1fba4ab0c786f7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
